FROM gocd/gocd-agent
MAINTAINER James Kirk <james.kirk84@gmail.com>

RUN \
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
  echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/3.12.0 main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list && \
  apt-get update

RUN apt-get install -y \
    mono-complete \
    fsharp \
    libtool \
    autoconf \
    g++ \
    gettext \
    make \
    default-jdk \
    cmake \
    git \
    wget \
    htop \
    pandoc \
    haskell-platform \
    ruby1.9.1 \
    xvfb \
    firefox &&\
    gem install bundler

RUN adduser go sudo

RUN mozroots --import --sync  &&\
    yes | certmgr --ssl -m https://go.microsoft.com &&\
    yes | certmgr -ssl -m https://nugetgallery.blob.core.windows.net &&\
    yes | certmgr -ssl -m https://nuget.org

# Install Xvfb 
ENV DISPLAY :99
ADD xvfb_init /etc/init.d/xvfb 
ADD xvfb-daemon-run /usr/bin/xvfb-daemon-run

RUN chmod a+x /etc/init.d/xvfb &&\
    chmod a+x /usr/bin/xvfb-daemon-run


